import os, discord, time
from discord.ext import commands
 
token = input(" Token: ")
client = commands.Bot(command_prefix="O", self_bot=True)

@client.command()
async def K(ctx):
    await ctx.send ('STUPID BITCH')
    await ctx.send ('NOW YOU FINNA GET BULLIED NOW')
    await ctx.send ('PUSSY YOUR MOM DONT LOVE YOU')
    await ctx.send ('YOUR GRANDMA FINEGRS HERSELF WITH CAT LITTER')
    await ctx.send ('YO LOOK AT THIS NIGGA LOLLLLL')
    await ctx.send ('FUCKING SHIT BAG')
    await ctx.send ('SON UR SO SHIT U 1 HOUR GOBLIN')
    await ctx.send ('SON HAS NO RIGHTS TO SPEAK')
    await ctx.send ('YOU ARE MY JR HOW U FEEL SEED')
    await ctx.send ('U SO ASS MY SON')
    await ctx.send ('UR GRANDMA GOT TORTURED BY KKK MEMBERS')
    await ctx.send ('MY BITCH LOL UR SO ASS')
    await ctx.send ('YOU SO ASS BOY')
    await ctx.send ('ILL RIP YOUR DOGS SPINE OUT YOUR BACK')
    await ctx.send ('FAT NECK ASS NERD')
    await ctx.send ('PUSSY ASS NIGGA YOU TRANNY FUCKER LOL')
    await ctx.send ('ILL WHOOP YOU WITH YOUR GRANDMAS SPINAL CORDS')
    await ctx.send ('SO FUCKING ASS BRO')
    await ctx.send ('U CANT DO SHIT ABOUT IT WEAK ASS NIGGA')
    await ctx.send ('OUTLAST ME BITCH ASS NIGGA')
    await ctx.send ('SON YOU SOME ASS LOL U CANT PACK')
    await ctx.send ('FOCUS PUSSY ASS NIGGA YOU SOME ASS')
    await ctx.send ('YOU SO ASS SON FIGHT BACK')
    await ctx.send ('YOU CANT LAST AGAINST ME')
    await ctx.send ('LAST AGAINST ME HAHAHA')
    await ctx.send ('WEAK ASS BITCH')
    await ctx.send ('NIGGA SO ASS PUSSY ASS BITCH YOU CANT BEAT ME')
    await ctx.send ('LOLLLLLLL')
    await ctx.send ('YOUR SO SHIT BITCH')
    await ctx.send ('ILL TORTURE YOUR MOMS TITTIES WITH MY DAGGER')
    await ctx.send ('U CANT DO SHIT ABOUT IT')
    await ctx.send ('LMAOOOOOOOOOOOOOOO')
    await ctx.send ('SUCH A BITCH FUCK NIGGA')
    await ctx.send ('FOCUS PUSSY ASS LOSER ASS ROBLOXIAN')
    await ctx.send ('YOUR A SHITBAG')
    await ctx.send ('DIDNT YOU RUN FROM ME????')
    await ctx.send ('YOU FOLDED LIKE A BITCH')
    await ctx.send ('LOLLLLLLLLLLLL')
    await ctx.send ('LMAOOOOOOOOOOOOOOO')
    await ctx.send ('BITCH PUSSY ASS NIGGA')
    await ctx.send ('FIGHT BACK')
    await ctx.send ('LMFAOOOOO')
    await ctx.send ('NIGGA SO ASS')
    await ctx.send ('TYPE FASTER NIGGA')
    await ctx.send ('YOUR HANDS GETTING TIRED????')
    await ctx.send ('WEAK ASS NIGGA BRUH LOL')
    await ctx.send ('SHITTY DICK ASS NIGGA')
    await ctx.send ('SON FIGHT BACK')
    await ctx.send ('SLEEP TO UR OVERLORD SONNY')
    await ctx.send ('UR SO SHIT HAHAHHAHAHA')
    await ctx.send ('IMA TORTURE UR GRANDMAS PUSSY WITH SATANS BLADE')
    await ctx.send ('DO SUM ABT IT PUSSY')
    await ctx.send ('YOU WILL NEVER BE ABLE TO BEAT ME')
    await ctx.send ('NIGGA ASS AS SHIT')
    await ctx.send ('ILL CHOKE SLAM YO GRANDMA')
    await ctx.send ('LOLLLLLLL')
    await ctx.send ('HE FELL ASLEEP LMAOAOAOAOAO')
    await ctx.send ('SON YOUR SO SHIT MY NIGGA')
    await ctx.send ('LMAOOOOOOOOO')
    await ctx.send ('UR SO ASS')
    await ctx.send ('FUCKIN CANCER PATIENT ASS NIGGA')
    await ctx.send (':nerd:')
    await ctx.send (':nerd:')
    await ctx.send (':nerd:')
    await ctx.send ('YOU WILL NOT LAST 0/80 HOURS')
    await ctx.send ('NO BREAKS FOR YOU BALD AASS NIGGA')
    await ctx.send ('LOL U CANT BEAT ME AT ALL')
    await ctx.send ('SONNY BOYYYYY')
    await ctx.send ('NO')
    await ctx.send ('BREAKS')
    await ctx.send ('FOR')
    await ctx.send ('U')
    await ctx.send ('PUSSY ASS NIGGA')
    await ctx.send ('ASS')
    await ctx.send ('NIGGA THOUGHT HE CAN PACK')
    await ctx.send ('YOU SO ASS PUSSY ASS NIGGA')
    await ctx.send ('YOU GETTING TORTURED RN')
    await ctx.send ('YOU CANT RUN FROM ME')
    await ctx.send ('JR KEEP CRYING')
    await ctx.send ('HOW U FEEL U COCK ROACH JUICE LICKER')
    await ctx.send ('CANT')
    await ctx.send ('OUTLAST')
    await ctx.send ('ME')
    await ctx.send ('NIGGA LOOKS LIKE SHA EK WITH TITTIES')
    await ctx.send ('YOUR SO SHIT MY JR')
    await ctx.send ('lMFAOOOO')
    await ctx.send ('YOU')
    await ctx.send ('SUCK')
    await ctx.send ('WEAK FAGGOT PUNK')
    await ctx.send ('SHITTER')
    await ctx.send ('NIGGA ASS ASF')
    await ctx.send ('FOCUS')
    await ctx.send ('ON')
    await ctx.send ('ME')
    await ctx.send ('GOBLIN')
    await ctx.send ('UR SO SHIT MY NIGGA')
    await ctx.send ('MY')
    await ctx.send ('DOG')
    await ctx.send ('SON')
    await ctx.send ('WEAK')
    await ctx.send ('FUCK BOY')
    await ctx.send ('YOU ARE MY SON PUSSY ASS BITCH')
    await ctx.send ('WEAK')
    await ctx.send ('ASS')
    await ctx.send ('NIGGA')
    await ctx.send ('HOW YOU FEEL FUCK NIGGA')
    await ctx.send ('YOU GET NO BITCHES BITCH ASS NIGGA')
    await ctx.send ('YOU EAT BELLY BUTTON SEMEN REATARDED ASS NIGGA')
    await ctx.send ('SON TYPE FASTER')
    await ctx.send ('YOU GET RAPED BY SATANIC ROACHES')
    await ctx.send ('ILL BITE YOUR HEART WITH MY FANGS')
    await ctx.send ('AND TORTURE YOU WITH MY DAGGER')
    await ctx.send ('U GET BREASTFED BY NIGERIAN MONKEYS')
    await ctx.send ('NIGGA GOT TORTURED BY MONGOLS')
    await ctx.send ('CORNY ASS NIGGA WAS ASKING ME FOR NUT VIDEOS')
    await ctx.send ('EWWWWWWWWWWWWWWWW')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send ('GRAB THE FUCKING BONE BITCH')
    await ctx.send (':bone: :bone:') 
    await ctx.send ('BARK DOGGIE')
    await ctx.send (':bone: :bone:')
    await ctx.send ('FAGGOT ASS NIGGA')
    await ctx.send ('SHOW 100$ RN')
    await ctx.send ('19')
    await ctx.send ('18')
    await ctx.send ('17')
    await ctx.send ('16')
    await ctx.send ('15')
    await ctx.send ('14')
    await ctx.send ('13')
    await ctx.send ('12')
    await ctx.send ('11')
    await ctx.send ('10')
    await ctx.send ('9')
    await ctx.send ('8')
    await ctx.send ('7')
    await ctx.send ('6')
    await ctx.send ('5')
    await ctx.send ('4')
    await ctx.send ('3')
    await ctx.send ('2')
    await ctx.send ('1')
    await ctx.send ('0')
    await ctx.send ('FOLDED PUSSY IM DONE WITH U NOW FUCK NIGGA')
    await ctx.send ('SIKE NIGGA YOU THOUGHT I WAS DONE WE RUNNING TILL 2030')
    await ctx.send ('LOL SON GOT BED BUGS')
    await ctx.send ('U STILL GET GOVERNMENT CHECKS EVERY WEEK POOR ASS NIGGA')
    await ctx.send ('LMFAOO')
    await ctx.send ('HOW U FEEL WEAK SHITTER')
    await ctx.send ('WEAK AVOCADO JUICE SNIFFER')
    await ctx.send ('U HOMELESS BILLY GOAT EATER')
    await ctx.send ('WEAK ASS ALLIGATOR CLIT SUCKER')
    await ctx.send ('COME DO SUM WEAK FAGGOT')
    await ctx.send ('NIGGA IS SO HORRIBLE LMFAO')
    await ctx.send ('EWWWWWWW')
    await ctx.send ('U FAGGOT ASS CUNT')
    await ctx.send ('YOUR MOM GOT FINGERED BY ZEUS')
    await ctx.send ('YOU FINGER ARMADILLOS WITH YOUR NIPPLES')
    await ctx.send ('NIGGA FINGERS JUGGERNAUTS')
    await ctx.send ('LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL')
    await ctx.send ('WEAK ASS 2 MINUTE GOBLIN')
    await ctx.send ('YOU LITERALLY DIED TO ME')
    await ctx.send ('YOU LICK DOG FECES')
    await ctx.send ('BIG HIPPO NUT EATER')
    await ctx.send ('WEAK NIGGA EATS GIRRAFEE SEMEN EVERY MORNING')
    await ctx.send ('SLOW FUCK LMFOA NIGGA CRYING RN')
    await ctx.send ('ILL LITERALLY CUT YOUR KIDNEYS INTO 700 PIECES')
    await ctx.send ('YOU ESEXD JOHN CENA ON ROBLOX')
    await ctx.send ('YOU GOT PENETRATED BY BARACK OBAMA')
    await ctx.send ('RAINBOW COLORED LADY BUG EATER')
    await ctx.send ('YOU GET FINGERED BY BAPHOMETS')
    await ctx.send ('YOU WORTHLESS FAGGOT')
    await ctx.send ('FUCKING JEW ASS NIGGA')
    await ctx.send ('LOOK AT THIS WEAK NIGGA CRYING')
    await ctx.send ('WEAK ASS NIGGA HOW U FEEL SON IMA KILL U')
    await ctx.send ('LAME QUEER')
    await ctx.send ('TAKE A SEAT SON')
    await ctx.send ('WEAK ASS FAGGOT YOU SUCK LOL')
    await ctx.send ('WAKE UP BITCH')
    await ctx.send ('WEAK NIGGA')
    await ctx.send ('IS A FUCKING CLOWN :clown:')
    await ctx.send ('SONNY BOY SHOW ME YOUR WRIST')
    await ctx.send ('UR NOT SAFE SHITTER')
    await ctx.send ('WHY DO U STILL CUT YOURSELF EVERYNIGHT')
    await ctx.send ('WEAK EMO ASS FAGGOT')
    await ctx.send ('HANG URSELF NIGGA')
    await ctx.send ('POOR ASS NIGGA CUTS HIMSELF')
    await ctx.send ('WEAK LAME FUCK IMA KILL U')
    await ctx.send ('YUP ILL CUT YOUR NECK IN HALF')
    await ctx.send ('SONNY BOY WAKE UP U NOT SAFE')
    await ctx.send ('HES SHAKING RN LMFAO')
    await ctx.send ('UR GOING IN MY VAULT SON')
    await ctx.send ('MY SON IS GONNA CRY LOL')
    await ctx.send ('LOL ILL HANG YOUR GRANDMA FROM A CELLING FAN AND TURN IT ON')
    await ctx.send ('NIGGA LICKS GREESY ARMPITS')
    await ctx.send ('YOU HAVE NO RIGHTS TO SPEAK NIGGER BOY')
    await ctx.send ('SO ASS MY SON')
    await ctx.send ('NIGGA FINGERS 70 YEAR OLD PUSSY')
    await ctx.send ('YOUR SO ASS') 
    await ctx.send ('YOURE GENGIS KHAN JR')
    await ctx.send ('YOUR SO FUCING ASS SON')
    await ctx.send ('NIGGA EATS RICE WITH HIS NIPPLES')
    await ctx.send ('WAKE UP NIGGA')
    await ctx.send ('SON IS SHAKING SO BAD RN')
    await ctx.send ('NIGGA GETS RAPED BY KKK MEMBERS')
    await ctx.send ('EWWWWWWWWWWWWWWWW')
    await ctx.send ('TYPE FASTER BITCH')
    await ctx.send ('COME DIE AGAIN discord.gg/chiefjustice')
    await ctx.send ('ILL TORTURE YOUR SISTER WITH SATANIC COCK ROACHES')
    await ctx.send ('SONNY WAS BEATING HIS DICK TO FURRY PORN')
    await ctx.send ('EWWWWW')
    await ctx.send ('NIGGA SO ASS FUCKING BITCH')
    await ctx.send ('FIGHT BACK SHITTER')
    await ctx.send ('SON  IS UNKNOWN ASF')
    await ctx.send ('SON SO FUCKING SHIT OML')
    await ctx.send ('YOU GOT DRY NIPPLES SON')
    await ctx.send ('BARK NIGGER')
    await ctx.send ('WEAK ASS NIGGA THOUGHT I WAS PLAYIN')
    await ctx.send ('LOLLLLLLLLL NIGGA GETS 10$ EVERY MONTH')
    await ctx.send ('NOT TAKIN U SERIOUS RN')
    await ctx.send ('U GOT A DRY SCALP')
    await ctx.send ('WEAK ASS NIGGA EATS DOG GUTS FOR FUN')
    await ctx.send ('ILL BEAT YOUR GRANDMA WITH MY DAGGER') 
    await ctx.send ('SON SO ASS PUSSY')
    await ctx.send ('GET MAD SONNY')
    await ctx.send ('UR A SCHOOL SHOOTER')
    await ctx.send ('LOLLLLLLLLLLLL')
    await ctx.send ('NIGGA DRINKS MILK OUT OF HAND SANATIZER BOTTLE')
    await ctx.send ('WEAKLING')
    await ctx.send ('YOUR GRANDMA COMITTED SUICIDE ON A TREADMIL')
    await ctx.send ('FUCK ASS NIGGA')
    await ctx.send ('HORRIBLE BITCH')
    await ctx.send ('ILL LITERALLY CUT YOUR DOGS JAW OPEN')
    await ctx.send ('PUSSY DO SUM')
    await ctx.send ('COME HERE NIGGER THIS IS YOUR PUNISHMENT')
    await ctx.send ('https://cdn.emojidex.com/emoji/seal/whip.png?1463158683')
    await ctx.send ('https://cdn.emojidex.com/emoji/seal/whip.png?1463158683')
    await ctx.send ('HAHAHA YOUR SO SHIT MY NIGGA')
    await ctx.send ('NIGGA FANS ME SO MUCH')
    await ctx.send ('YOU EAT ISHOWSPEEDS MOMS SEMEN EVERYDAY')
    await ctx.send ('SON CLEANS UNDER HIS GRANDMAS TOENAILS EVERY WEEK')
    await ctx.send ('EWWWWWWWWWWWWWWWWWWWWWWWWWWW')
    await ctx.send ('YOU ARE DISGUSTING AS FUCK')
    await ctx.send ('NIGGA SUCKS GORILLA BELLY BUTTON') 
    await ctx.send ('NIGGA NASTY AS SHIT MY NIGGA')
    await ctx.send ('LOLLLLLLLLLLLLLL')
    await ctx.send ('LMAOOOOOOOOOOOOOO')
    await ctx.send ('SON IS SO TERRIBLE')
    await ctx.send ('SON LOOKS LIKE LOGAN PAUL WITH TITTES')
    await ctx.send ('U GET NO PAY CHECKS POOR ASS NIGGA')
    await ctx.send ('NIGGA LICKS THIZZKIDS SPIT EVERYDAY')
    await ctx.send ('U UGLY ASF MY NIGGA')
    await ctx.send ('SHOW UR FACE RN 20')
    await ctx.send ('19')
    await ctx.send ('18')
    await ctx.send ('17')
    await ctx.send ('16')
    await ctx.send ('15')
    await ctx.send ('14')
    await ctx.send ('13')
    await ctx.send ('12')
    await ctx.send ('11')
    await ctx.send ('10')
    await ctx.send ('9')
    await ctx.send ('8')
    await ctx.send ('7')
    await ctx.send ('6')
    await ctx.send ('5')
    await ctx.send ('4')
    await ctx.send ('3')
    await ctx.send ('2')
    await ctx.send ('1')
    await ctx.send ('0')
    await ctx.send ('QUEER ASS DIRTY EMO BASTARD U THOUGHT WE WAS COOL?')
    await ctx.send ('SHITTERBOY KEEP UP WITH ME DIRTY FROG SHUT THE FUCK UP 4 EYED SHITSKIN')
    await ctx.send ('ILL SHOVE MY DAGGER DOWN YOUR GRANDMA THROAT AND TORTURE HER GUTS')
    await ctx.send ('SONNY SO ASS')
    await ctx.send ('LMFAOOOOOOOOOOOO')
    await ctx.send ('NO BITCHES + NO FUNDS')
    await ctx.send ('HOW U FEEL SON')
    await ctx.send ('IM FLAMING YOU RN')
    await ctx.send ('LMAOOOOOOOOOOOOOO')
    await ctx.send ('LETS STAM IN discord.gg/chiefjustice')
    await ctx.send ('YOUR SHITTY BOY')
    await ctx.send ('UR SO ASSSSSSSSS')
    await ctx.send ('DONT U EVER TRY TO PRESS ME AGAIN SON')
    await ctx.send ('SON GET THE BANANA MONKEY NIGGER')
    await ctx.send (':banana: :banana:')
    await ctx.send ('GET THE BANANA SLAVE MONKEY NIGGER')
    await ctx.send (':banana: :banana:')
    await ctx.send ('LOLLL UR SO SHIT')
    await ctx.send ('ILL CUT UR GRANDMAS CHEST OPEN')
    await ctx.send ('AND PLAY VOLLEY BALL WITH HER ORAGNS AND HER HEART')
    await ctx.send ('STUPID ASS PUNK')
    await ctx.send ('YOU NOT SAVE AT ALL RN SON')
    await ctx.send ('IM NOT GIVIN U NO MORE CLOUT')
    await ctx.send ('THIS IS UR DEMISE U SEA MONKEY')
    await ctx.send ('U CANT LAST 70+ HOURS WITH ME SON FOCUS UP BITCH ASS NIGGA')
    await ctx.send ('HOCUS POCUS I COMMAND YOU TO FOCUS')
    await ctx.send ('ILL TIE YOUR GRANDMA DOWN TO A PENTAGRAM')
    await ctx.send ('AND SUMON A DEMON IN THAT BITCH')
    await ctx.send ('THEN IMA SHOVE MY KNIFE HER PUSSY')
    await ctx.send ('CRY MORE ABOUT IT SON')
    await ctx.send ('YOU CANT PACK FUCK NIGGA')
    await ctx.send ('NIGGA IM FLAMING YO SHIT RN BOY')
    await ctx.send ('DO SUM ABT IT')
    await ctx.send ('STAY IN A NIGGERS PLACE MONKEY')
    await ctx.send ('FUCKING LOSER')
    await ctx.send ('YOU LIKE TOE NAIL SEMEN EWWWWWW')
    await ctx.send ('SON SO ASS')
    await ctx.send ('SON THINKS HE CAN END HIS GOD')
    await ctx.send ('MY SON FOCUS THE FUCK UP AND COME DIE TO YOUR GOD')
    await ctx.send ('YOU EAT GORILLA SNOT')
    await ctx.send ('EWWWWWWWWWWWWWWWWWWWW')
    await ctx.send ('YOU GORILLA NIPPLE SUCKER')
    await ctx.send ('YOU NASTY ASF')
    await ctx.send ('EWWWWWWW LMFAOOOOOOOOOOO')
    await ctx.send ('UR LITERALLY MY SON')
    await ctx.send ('LOLLLLLLLLL')
    await ctx.send ('U STILL GET 5$ PAY CHECKS')
    await ctx.send ('POOR ASS BITCH')
    await ctx.send ('WEAK ASS PORCH MONKEY')
    await ctx.send ('COME DIE FAGGOT')
    await ctx.send ('COME LAST 100 HOURS')
    await ctx.send ('YOU HAVE PEPPERONI SLICES AS YOUR NIPPLES')
    await ctx.send ('EWWWWWWWWWWWWWWWWWWWWWW')
    await ctx.send ('WEAK ASS NIGGA')
    await ctx.send ('DONT EVER CALL ME OUT BITCH')
    await ctx.send ('YOU LOOK LIKE KAY FLOCK WITH TITTIES BITCH')
    await ctx.send ('STFU SLUT')
    await ctx.send ('YOUR AN E-KITTEN')
    await ctx.send ('EWWWWWWWW')
    await ctx.send ('NIGGA THOUGHT HE CAN PACK')
    await ctx.send ('FALL ASLEEP SON')
    await ctx.send ('LOLLLL HE IS ASLEEP')
    await ctx.send ('AFK CHECK DONT SLEEP')
    await ctx.send ('1 :middle_finger:')
    await ctx.send ('2 :middle_finger:')
    await ctx.send ('3 :middle_finger:')
    await ctx.send ('4 :middle_finger:')
    await ctx.send ('5 :middle_finger:')
    await ctx.send ('6 :middle_finger:')
    await ctx.send ('7 :middle_finger:')
    await ctx.send ('8 :middle_finger:')
    await ctx.send ('9 :middle_finger:')
    await ctx.send ('10 :middle_finger:')
    await ctx.send ('11 :regional_indicator_f:')
    await ctx.send ('12 :regional_indicator_o:')
    await ctx.send ('13 :regional_indicator_c:')
    await ctx.send ('14 :regional_indicator_u:')
    await ctx.send ('15 :regional_indicator_s:')
    await ctx.send ('16 :regional_indicator_p:')
    await ctx.send ('17 :regional_indicator_u:')
    await ctx.send ('18 :regional_indicator_s:')
    await ctx.send ('19 :regional_indicator_s:')
    await ctx.send ('20 :regional_indicator_y:')
    await ctx.send ('LOL FOLDED SON CLIPPED EZ U FOLDED TO RYZE')
    await ctx.send ('GORRILLA SHIT FACE 💩💩💩')
    await ctx.send ('LAME ASS DIPSHIT BAFOON BUM ASS SISSY CUNT SUCKIN GORRILLA SHIT FACE')
    await ctx.send ('I OWN U SON YUP CRY FOCUS AND COPE TO ME HARDER BITCH UR NOTHING BITCHBOY I RUN U SON C ME AND SALUTE TO ME 🖕🖕')
    await ctx.send ('SON SMELLS LIKE WET MONKEY NUT SACKS')
    await ctx.send ('YOU SMELL LIKE MONKEY SEMEN')
    await ctx.send ('NIGGA SO SHITTY')
    await ctx.send ('U CANT PRESS ME SON GET BACK FUCK BOY I OWN YOU')
    await ctx.send ('WEAK ASS NIGGA TRIED TO CALL ME OUT BITCH')
    await ctx.send ('U MY JR FUCK BOY')
    await ctx.send ('ID FUCK UP YOUR ENTIRE BLOODLINE')
    await ctx.send ('WAKE')
    await ctx.send ('UP')
    await ctx.send ('AND')
    await ctx.send ('FIGHT')
    await ctx.send ('BACK')
    await ctx.send ('SHITTER')
    await ctx.send ('FOCUS ON YOUR MATA ILL RUN YOU OFF DISCORD')
    await ctx.send (':regional_indicator_f:')
    await ctx.send (':regional_indicator_u:')
    await ctx.send (':regional_indicator_c:')
    await ctx.send (':regional_indicator_k:')
    await ctx.send (':regional_indicator_e:')
    await ctx.send (':regional_indicator_r:')
    await ctx.send ('LOLLL HOW YOU FEEL GETTING PRESSED RN SON')
    await ctx.send ('YOU HAD NO ESCAPE PLAN')
    await ctx.send ('FUCK BOY')
    await ctx.send ('U CANT ESCAPE FROM ME')
    await ctx.send ('HAHAAHAHAHAH')
    await ctx.send ('YOUR SO SHITTY')
    await ctx.send ('YOUR A FOUREYED SHITSKIN')
    await ctx.send ('DO SUM ABT IT')
    await ctx.send ('TYPE FASTER BITCH ASS BOY')
    await ctx.send ('YOUR HANDS ARE TRIED ASF RN')
    await ctx.send ('YOU CANT KEEP UP WITH ME SONNY BOY FUCK OFF LOG OFF')
    await ctx.send ('BITCH ASS NIGGA')
    await ctx.send ('HOW U FEEL RN SON')
    await ctx.send ('ILL RIP YOUR GRANDMAS SPINE OUT OF HER BACK')
    await ctx.send ('BITCH ASS NIGGA')
    await ctx.send ('IMA PLAY CATCH WITH HER GUTS')
    await ctx.send ('BITCH ASS BOY')
    await ctx.send ('CMON FIGHT BACK')
    await ctx.send ('WHATS THE MATTER???')
    await ctx.send ('CANT FOCUS ON ME BITCH ASS NIGGA????')
    await ctx.send ('OLOLLOLOLLOLOL')
    await ctx.send ('LMAOOOOOOOOOOOO')
    await ctx.send ('YOU REALLY THOUGHT YOU CAN CALL ME OUT???')
    await ctx.send ('YOUR SO SHIT MY NIGGA')
    await ctx.send ('COME DIE discord.gg/chiefjustice')
    await ctx.send ('DONT DUCK SONNY BOY')
    await ctx.send ('LOLLLLLLLLLLLLLLLLL')
    await ctx.send ('YOU GETTING TORUTED RN')
    await ctx.send ('ILL PENATRATE YOUR GRANDMAS TITS WITH A BLOODY BLADE')
    await ctx.send ('BITCH ASS NIGGA')
    await ctx.send ('YOUR BALLS SMELL LIKE WET SEA MONKEY SEX')
    await ctx.send ('BITCH AS NIGGA THOUGHT HE WAS SAFE')
    await ctx.send ('YOU NOT SAFE AT ALL MY NIGGA')
    await ctx.send ('BITCH ASS FAGGOT')
    await ctx.send ('FUCK WRONG WITH THIS NIGGA')
    await ctx.send ('NIGGA YOU NOT SAFE AT ALL')
    await ctx.send ('BALD ASS NIGGA')
    await ctx.send ('ILL TOTURE YOUR GRANDMAS PUSSY WITH GREESY MILK')
    await ctx.send ('RETARDED ASS NIGGA')
    await ctx.send ('YOOOOOOOOOOO')
    await ctx.send ('YOU LICK UNDER YOUR MOMS FINGER NAILS EVERY NIGHT')
    await ctx.send ('ILL RIP YOUR MOMS BELLY BUTTON OUT')
    await ctx.send ('DO SUM ABT IT')
    await ctx.send ('CANT DO SHIT')
    await ctx.send ('BITCH AS NIGGA')
    await ctx.send ('WYD SON')
    await ctx.send ('YOU CANT LAST 100 HOURS YOU GOT SCHOOL TMR BITCH')
    await ctx.send ('YOU SO FUCKING SHITTY')
    await ctx.send ('HOW U FEEL U GETTING PRESSED ON DISCORD.COM LOLLLLL')
    await ctx.send ('FAGGOT ASS NIGGA')
    await ctx.send ('YOUR MOM GETS TORTURED BY RAZOR BLADES')
    await ctx.send ('FAGGOT NIGGA')
    await ctx.send ('HOW U FEEL U GETTING BULLIED RN')
    await ctx.send ('LMAAAOAOAOAOAOA')
    await ctx.send ('U CANT EVEN MANAGE TO GET 100$ YET')
    await ctx.send ('SHOW 100$')
    await ctx.send ('1')
    await ctx.send ('2')
    await ctx.send ('3')
    await ctx.send ('4')
    await ctx.send ('5')
    await ctx.send ('6')
    await ctx.send ('7')
    await ctx.send ('8')
    await ctx.send ('9')
    await ctx.send ('10')
    await ctx.send ('11')
    await ctx.send ('12')
    await ctx.send ('13')
    await ctx.send ('14')
    await ctx.send ('15')
    await ctx.send ('16')
    await ctx.send ('17')
    await ctx.send ('18')
    await ctx.send ('19')
    await ctx.send ('20')
    await ctx.send ('POOR ASS NIGGA')
    await ctx.send ('FOCUS YOU SHITSKIN')
    await ctx.send ('U CANT EVEN PULL A LATINA AND U SPEAKING TO ME SON')
    await ctx.send ('COME DIE discord.gg/justiceontop')
    await ctx.send ('DIDNT U FOLD TO ME IN 17 HOURS?')
    await ctx.send ('U ASS ASF MY NIGGA')
    await ctx.send ('DAD CHECK')
    await ctx.send ('1')
    await ctx.send ('2')
    await ctx.send ('3')
    await ctx.send ('4')
    await ctx.send ('5')
    await ctx.send ('6')
    await ctx.send ('7')
    await ctx.send ('8')
    await ctx.send ('9')
    await ctx.send ('10')
    await ctx.send ('NOW IM DONE WITH YOU PUSSY')
    await ctx.send ('SIKE NIGGA YOU THOUGHT I WAS DONE?')
    await ctx.send ('now im finna press you non caps')
    await ctx.send ('bitch ass nigga')
    await ctx.send ('your grandma gets raped by satanic monkeys')
    await ctx.send ('retarded ass nigga')
    await ctx.send ('LOLLLLLLL')
    await ctx.send ('BACK TO CAPS LOCK PUSSY')
    await ctx.send ('DO SUM ABT IT FUCK BOY')
    await ctx.send ('U CANT OUTLAST ME PUSSY')
    await ctx.send ('COME DIE')
    await ctx.send ('FUCK NIGGA')
    await ctx.send ('TYPE FASTER PUSSY BOY')
    await ctx.send ('ILL RUN YOU OFF DISCORD SON')
    await ctx.send ('DO SUM ABT IT')
    await ctx.send ('LMOAOAOAOAOAOA')
    await ctx.send ('UR SO SHITTY MY SON')
    await ctx.send ('DO SUM ABT IT')
    await ctx.send ('FUCK NIGGA')
    await ctx.send ('THOUGHT I WAS PLAYIN LOL')
    await ctx.send ('YOU LOOK LIKE YUS GZ WITH TITTIES')
    await ctx.send ('FUCK NIGGA LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL')
    await ctx.send ('YOU HAVE A MICROPENIS WITH FRECKLES')
    await ctx.send ('WEAK ASS NIGGA :middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send ('DO SUM PUSSY')
    await ctx.send ('GET PRESSED FUCK NIGGA')
    await ctx.send ('ILL BASH YOUR AUNTS SKULL')
    await ctx.send ('FUCK NIGGA')
    await ctx.send ('YOU GET RAPED BY SATANIC 4TH GRADERS')
    await ctx.send ('BITCH ASS NIGGA')
    await ctx.send ('NIGGA CANT PRESS ME LOLLLL')
    await ctx.send ('YOU SPIDER VERSE SKINTONE COSPLAYER')
    await ctx.send ('ILL RIP YOUR SOUL OUT YO SKINNY ASS BROOM STICK ASS BODY')
    await ctx.send ('U SUCK ASS WEAK FEMINE GORILLA DOGGY SAY PLEASE RYZE DONT RUN ME OFF DISCORD LOL LOL RAT FACE FUCK')
    await ctx.send ('AHHHHHHHH YOU UGLY BITCH YOU STINK LIKE A NARCOTIC COCNUT')
    await ctx.send ('ILL SMOKE YOU INTO ABYSS')
    await ctx.send ('YOU SHITLING')
    await ctx.send ('ILL SCORCH YOU')
    await ctx.send ('WHERES YOUR EGO')
    await ctx.send ('CORNBALL YOUR SO SHIT')
    await ctx.send ('PUSSY ASS LIL NIGGA')
    await ctx.send ('YOU FUCK GOAT VAGINA')
    await ctx.send ('EWWWWWWWWWWWWWWWWW')
    await ctx.send ('RETARDED MONKEY STFU PUSSY')
    await ctx.send ('YOU UGLY ASF MY NIGGA')
    await ctx.send ('COME PACK ABOUT IT FUCK NIGGA')
    await ctx.send ('ILL TORTURE YOUR MOMS PUSSY')
    await ctx.send ('ILL SLICE YOUR NIPPLES OFF YOUR CHEST')
    await ctx.send ('UGLY ASS NIGGA')
    await ctx.send ('CRY BABY ASS NIGGA')
    await ctx.send ('KEEP CRYING TO YOUR OVERLORD SONNY')
    await ctx.send ('STOP COMPLAINING AND PACK BACK PUSSY ASS NIGGER')
    await ctx.send ('YOUR BLACK SON YOU AFRICAN ASHY SLAVE')
    await ctx.send ('NIGGA HAS DRY SKIN')
    await ctx.send ('QUEER ASS BITCH')
    await ctx.send ('NIGGA RETARDED AS SHIT')
    await ctx.send ('CRY ABOUT IT')
    await ctx.send ('NIGGA GETTING PRESSED ON DISCORD')
    await ctx.send ('LMAOOOOOOOOOOOOOOOOOOOOOO')
    await ctx.send ('NOBODY ON A AUTO PRESSURE THIS IS ME TYPING PUSSY')
    await ctx.send ('AFK CHECK DONT FOLD NIGGER')
    await ctx.send ('1 :middle_finger:')
    await ctx.send ('2 :middle_finger:')
    await ctx.send ('3 :middle_finger:')
    await ctx.send ('4 :middle_finger:')
    await ctx.send ('5 :middle_finger:')
    await ctx.send ('6 :middle_finger:')
    await ctx.send ('7 :middle_finger:')
    await ctx.send ('8 :middle_finger:')
    await ctx.send ('9 :middle_finger:')
    await ctx.send ('10 :middle_finger:')
    await ctx.send ('11 :regional_indicator_f:')
    await ctx.send ('12 :regional_indicator_o:')
    await ctx.send ('13 :regional_indicator_c:')
    await ctx.send ('14 :regional_indicator_u:')
    await ctx.send ('15 :regional_indicator_s:')
    await ctx.send ('16 :regional_indicator_p:')
    await ctx.send ('17 :regional_indicator_u:')
    await ctx.send ('18 :regional_indicator_s:')
    await ctx.send ('19 :regional_indicator_s:')
    await ctx.send ('20 :regional_indicator_y:')
    await ctx.send ('21 :middle_finger:')
    await ctx.send ('22 :middle_finger:')
    await ctx.send ('23 :middle_finger:')
    await ctx.send ('24 :middle_finger:')
    await ctx.send ('25 :middle_finger:')
    await ctx.send ('26 :middle_finger:')
    await ctx.send ('27 :middle_finger:')
    await ctx.send ('28 :middle_finger:')
    await ctx.send ('29 :middle_finger:')
    await ctx.send ('30 :middle_finger:')
    await ctx.send ('31 :middle_finger:')
    await ctx.send ('32 :middle_finger:')
    await ctx.send ('33 :middle_finger:')
    await ctx.send ('34 :middle_finger:')
    await ctx.send ('35 :middle_finger:')
    await ctx.send ('36 :middle_finger:')
    await ctx.send ('37 :middle_finger:')
    await ctx.send ('38 :middle_finger:')
    await ctx.send ('39 :middle_finger:')
    await ctx.send ('40 :middle_finger:')
    await ctx.send ('41 :middle_finger:')
    await ctx.send ('42 :middle_finger:')
    await ctx.send ('43 :middle_finger:')
    await ctx.send ('44 :middle_finger:')
    await ctx.send ('45 :middle_finger:')
    await ctx.send ('46 :middle_finger:')
    await ctx.send ('47 :middle_finger:')
    await ctx.send ('48 :middle_finger:')
    await ctx.send ('49 :middle_finger:')
    await ctx.send ('50 :middle_finger:')
    await ctx.send ('51 :middle_finger:')
    await ctx.send ('52 :middle_finger:')
    await ctx.send ('53 :middle_finger:')
    await ctx.send ('54 :middle_finger:')
    await ctx.send ('55 :middle_finger:')
    await ctx.send ('56 :middle_finger:')
    await ctx.send ('57 :middle_finger:')
    await ctx.send ('58 :middle_finger:')
    await ctx.send ('59 :middle_finger:')
    await ctx.send ('60 :middle_finger:')
    await ctx.send ('61 :middle_finger:')
    await ctx.send ('62 :middle_finger:')
    await ctx.send ('63 :middle_finger:')
    await ctx.send ('64 :middle_finger:')
    await ctx.send ('65 :middle_finger:')
    await ctx.send ('66 :middle_finger:')
    await ctx.send ('67 :middle_finger:')
    await ctx.send ('68 :middle_finger:')
    await ctx.send ('69 :middle_finger:')
    await ctx.send ('70 :middle_finger:')
    await ctx.send ('71 :middle_finger:')
    await ctx.send ('72 :middle_finger:')
    await ctx.send ('73 :middle_finger:')
    await ctx.send ('74 :middle_finger:')
    await ctx.send ('75 :middle_finger:')
    await ctx.send ('76 :middle_finger:')
    await ctx.send ('77 :middle_finger:')
    await ctx.send ('78 :middle_finger:')
    await ctx.send ('79 :middle_finger:')
    await ctx.send ('80 :middle_finger:')
    await ctx.send ('81 :regional_indicator_j:')
    await ctx.send ('82 :regional_indicator_u:')
    await ctx.send ('83 :regional_indicator_s:')
    await ctx.send ('84 :regional_indicator_t:')
    await ctx.send ('85 :regional_indicator_i:')
    await ctx.send ('86 :regional_indicator_c:')
    await ctx.send ('87 :regional_indicator_e:')
    await ctx.send ('88 :regional_indicator_o:')
    await ctx.send ('89 :regional_indicator_w:')
    await ctx.send ('90 :regional_indicator_n:')
    await ctx.send ('91 :regional_indicator_s:')
    await ctx.send ('92 :regional_indicator_y:')
    await ctx.send ('93 :regional_indicator_o:')
    await ctx.send ('94 :regional_indicator_u:')
    await ctx.send ('95 :regional_indicator_f:')
    await ctx.send ('96 :regional_indicator_a:')
    await ctx.send ('97 :regional_indicator_g:')
    await ctx.send ('98 :regional_indicator_g:')
    await ctx.send ('99 :regional_indicator_o:')
    await ctx.send ('100 :regional_indicator_t:')
    await ctx.send ('LOLLLL TYPE FASTER U FOLDED FUCK BOY')
    await ctx.send ('YOU SOME SHIT')
    await ctx.send ('HOW YOU FEEL WEAK SHITTER')
    await ctx.send ('AHHHHHHHHHHHHHHHH')
    await ctx.send ('YOUR SO ASS MY NIGGA')
    await ctx.send ('CMON SON TYPE FASTER')
    await ctx.send ('weak ass nigga')
    await ctx.send ('you eat goat spinal cords')
    await ctx.send ('you my son LOLLLLL')
    await ctx.send ('how you feel weak ass nigga')
    await ctx.send ('suck my dick sideways pussy')
    await ctx.send ('nigga so ass')
    await ctx.send ('who is this nigga yo?')
    await ctx.send ('im pressing you non caps rn')
    await ctx.send ('look at my son on his knees begging me not to fold him')
    await ctx.send ('lollll')
    await ctx.send ('look at my seedling')
    await ctx.send ('ill slit your face into small pieces')
    await ctx.send ('bitch ass nigga boy')
    await ctx.send ('niggas faggot feoon femboy')
    await ctx.send ('fucking retard')
    await ctx.send ('do sum abt it rn')
    await ctx.send ('you muslim femboy')
    await ctx.send ('ugly as nigga')
    await ctx.send ('you getting bullied rn lol')
    await ctx.send ('do sum abt it pussy boy')
    await ctx.send ('stupid ass nigga')
    await ctx.send ('dont you ever call me out ever again bitch')
    await ctx.send ('lollll')
    await ctx.send ('cant take dis nigga serious im done with this nigga')
    await ctx.send ('LOL RETARDED ASS NIGGA')
    await ctx.send ('██████╗░██████╗░███████╗░██████╗░██████╗██╗░░░██╗██████╗░███████╗')
    await ctx.send ('██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝██║░░░██║██╔══██╗██╔════╝')
    await ctx.send ('██████╔╝██████╔╝█████╗░░╚█████╗░╚█████╗░██║░░░██║██████╔╝█████╗░░')
    await ctx.send ('██╔═══╝░██╔══██╗██╔══╝░░░╚═══██╗░╚═══██╗██║░░░██║██╔══██╗██╔══╝░░')
    await ctx.send ('██║░░░░░██║░░██║███████╗██████╔╝██████╔╝╚██████╔╝██║░░██║███████╗')
    await ctx.send ('╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═════╝░╚═════╝░░╚═════╝░╚═╝░░╚═╝╚══════╝')
    await ctx.send ('THIS NIGGA FR ASS')
    await ctx.send ('FUCKING PUSSY')
    await ctx.send ('U ASS ASF WEAK ASS NIGGA')
    await ctx.send ('WEAK ASS BITCH')
    await ctx.send ('FUCK UP UGLY ASS NIGGA')
    await ctx.send ('FOCUS UGLY ASS NIGGA')
    await ctx.send ('YOU SOME SHIT')
    await ctx.send ('ILL SLIT YOUR GRANDMAS LIPS OPEN')
    await ctx.send ('SON DO SUM ABOUT IT')
    await ctx.send ('I OWN YOU SON LOL')
    await ctx.send ('CRY MORE ABOUT IT FOR ALL I CARE')
    await ctx.send ('UR MY JR SONNY BOY')
    await ctx.send ('UR SO SHITTY')
    await ctx.send ('MY SON FIGHT BACK')
    await ctx.send ('IM BOUTTA BULLY YOU IN ARABIC')
    await ctx.send (' حتى الحمار ابن اللعنة قبالة الكلبة')
    await ctx.send ('ابن يتيح حزم لك الرعشة')
    await ctx.send ('LOLLL now im done with this ugly ass nigga')
    await ctx.send ('YOU A 80 YEAR OLD DOBBERMEN')
    await ctx.send ('ILL SKIN YOUR GRANDMA ALIVE')
    await ctx.send ('YOU SOME ASS LOLLLLLL')
    await ctx.send ('WEAK ASS PUNK')
    await ctx.send ('FUCK UP NIGGA STOP CRYING')
    await ctx.send ('FOCUS PUSSY YOU CANT EVEN LAST AN HOUR')
    await ctx.send ('TF THIS LIL NIGGA THINK HE TALKING TO')
    await ctx.send ('U SO SHIT MY SON')
    await ctx.send ('SON GETS RAPED BY JAMACIAN GANG BANGERS')
    await ctx.send ('I OWN YOUR BLOODLINE PUSSY')
    await ctx.send ('FIGHT BACK')
    await ctx.send ('AFK CHECK SON')
    await ctx.send ('1 JUSTICE')
    await ctx.send ('2 JUSTICE')
    await ctx.send ('3 JUSTICE')
    await ctx.send ('4 JUSTICE')
    await ctx.send ('5 JUSTICE')
    await ctx.send ('6 JUSTICE')
    await ctx.send ('7 JUSTICE')
    await ctx.send ('8 JUSTICE')
    await ctx.send ('9 JUSTICE')
    await ctx.send ('10 JUSTICE')
    await ctx.send ('11 JUSTICE')
    await ctx.send ('12 JUSTICE')
    await ctx.send ('13 JUSTICE')
    await ctx.send ('14 JUSTICE')
    await ctx.send ('15 JUSTICE')
    await ctx.send ('16 JUSTICE')
    await ctx.send ('17 JUSTICE')
    await ctx.send ('18 JUSTICE')
    await ctx.send ('19 JUSTICE')
    await ctx.send ('20 JUSTICE')
    await ctx.send ('LOLLLLL SON FOLDED')
    await ctx.send ('BITCH BOY SMD SIDEWAYS')
    await ctx.send ('YOUR GRANDMA IS A ASHY SHITSKIN AFRICAN')
    await ctx.send ('FOCUS UGLY ASS NIGGA')
    await ctx.send ('SON CANT FOCUS')
    await ctx.send ('DONT FOLD IN 1000 HOURS')
    await ctx.send ('LOLLLLLLLL')
    await ctx.send ('SHOW 50$ RN')
    await ctx.send ('1')
    await ctx.send ('2')
    await ctx.send ('3')
    await ctx.send ('4')
    await ctx.send ('5')
    await ctx.send ('6')
    await ctx.send ('7')
    await ctx.send ('8')
    await ctx.send ('9')
    await ctx.send ('10')
    await ctx.send ('11')
    await ctx.send ('12')
    await ctx.send ('13')
    await ctx.send ('14')
    await ctx.send ('15')
    await ctx.send ('16')
    await ctx.send ('17')
    await ctx.send ('18')
    await ctx.send ('19')
    await ctx.send ('20')
    await ctx.send ('LOL POOR ASS NIGGA')
    await ctx.send ('YOU CUT YOURSELF STILL')
    await ctx.send ('FUCKING SHITSKIN SHITLING')
    await ctx.send ('YOUR SHITTY BOY')
    await ctx.send ('NERD ASS NIGGA')
    await ctx.send ('UR ASS SON')
    await ctx.send ('ILL BITE YOUR GRANDMAS PUSSY WITH MY FANGS')
    await ctx.send ('YOU CANT LAST AGAINST ME')
    await ctx.send ('ILL PUSH YOUR GRANDMA INTO A MEAT GRINDER')
    await ctx.send ('YOU ARE ASS MY NIGGA')
    await ctx.send ('ILL PUSH YOU INTO BLINDER')
    await ctx.send ('LOLLLLLLLLLLLLLLL')
    await ctx.send ('YOU SO ASS')
    await ctx.send ('NIGGA SUCKS GORILLA PENIS')
    await ctx.send ('HOW YOU FEEL WEAK ASS PUNK LOL')
    await ctx.send ('PUSSY ASS NIGGA')
    await ctx.send ('NIGGA SMELLS LIKE PERIOD BLOOD')
    await ctx.send ('SHITTY ASS BASTARD')
    await ctx.send ('ILL SHOOT YOUR AUNT IN THE THROAT WITH A 12-GAUGE BARREL')
    await ctx.send ('YOUR SO ASS')
    await ctx.send ('LETS COMPARE FUNDS RN')
    await ctx.send ('QUIT FUCKING CATS')
    await ctx.send ('YOU LICK YOUR DOGS ANUS EVERYDAY')
    await ctx.send ('DISGUSTING FUCK')
    await ctx.send ('OUTLAST ME RN')
    await ctx.send ('YOUR MY SEEDLING')
    await ctx.send ('IM YOUR GOD SON CRY')
    await ctx.send ('NIGGA IS A DOG ANUS LOVER')
    await ctx.send ('SON THINKS HE CAN END HIS GOD')
    await ctx.send ('YOU CANT END ME FUCK NIGGA')
    await ctx.send ('SUCK MY NUTS UPSIDE DOWN')
    await ctx.send ('WEAK ASS FAGGOT')
    await ctx.send ('YOU GETTING BULLIED')
    await ctx.send (':rofl:')
    await ctx.send ('FOCUS SONNY BOY')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send (':middle_finger: :clown: :middle_finger:')
    await ctx.send ('JUSTIC OWNS YOU BITCH')
    await ctx.send ('LAME ASS NIGGA COME PACK discord.gg/chiefjustice')
    await ctx.send ('YOU SO ASS BOY')
    await ctx.send ('NIGGA LIKES GOAT PENIS')
    await ctx.send ('YOUR SHITTY BOY')
    await ctx.send ('ILL LITERALLY SLICE YOUR TIP OFF')
    await ctx.send ('YOU GETTING TORTURED RN')
    await ctx.send ('CRAMPS')
    await ctx.send ('NEVER')
    await ctx.send ('SEEN')
    await ctx.send ('SOMEONE')
    await ctx.send ('THIS')
    await ctx.send ('ASS')
    await ctx.send ('UR')
    await ctx.send ('SO')
    await ctx.send ('SHIT')
    await ctx.send ('U')
    await ctx.send ('MY')
    await ctx.send ('SON')
    await ctx.send ('NIGGA')
    await ctx.send ('TYPE')
    await ctx.send ('BACK')
    await ctx.send ('TRASH')
    await ctx.send ('ASS')
    await ctx.send ('COON YOU SO SHITTY')
    await ctx.send ('WEAK ASS NIGGA ID CUT YOUR GRANDMAS NIPPLES OFF')
    await ctx.send ('FUCK NIGGA GOT HIS NUTS IN HIS STOMACH')
    await ctx.send ('FUCKING SHITLING')
    await ctx.send ('ILL RIP UR EYELIDS OFF')
    await ctx.send ('ILL ASSASSINATE UR ENTIRE FAMILY WITH AN AXE')
    await ctx.send ('COME AND PLEAD WITH THE LORD')
    await ctx.send ('TWIGGY UNDERWEIGHT SKINNY FEMBOY I KNOW U NOT TRYNA PRESS ME')
    await ctx.send ('AYE COME DO SUM THEN PUSSY IM TIRED OF YO LAME ASS')
    await ctx.send ('LITTLE BLACK BITCH ILL BEAT THE SHIT OUTTA U U BETTER NOT FOLD')
    await ctx.send ('KEEP UP WITH ME SHITTY SHITTER MCSHITTERSON')
    await ctx.send ('TOO SLOW BITCH WHY U NOT ANSWERING ME COW GIRL')
    await ctx.send ('GET ON YOUR NEES AND SALUTE ME SON COME SEE ME AND BEG FOR MERCY')
    await ctx.send ('SHITTER BOY SISSY SHITTER BOY OUTLAST ME SON YOUR FUCKING SHIT CUNT')
    await ctx.send ('I CAN SMELL YOUR FEAR SON COME DIE UR SOME SHIT U CANT TYPE LIKE ME KEEEP UP')
    await ctx.send ('WHERE DO U THINK UR RUNNING TOO DIRTY BITCH TIME TO DIE')
    await ctx.send ('ILL DO JUMP ROPES WITH YOUR VEINS WEAK NIGGA')
    await ctx.send ('LOOK AT YOU SON UR NOT SAFE BETTER RUN AND HIDE WHILE U STILL CAN')
    await ctx.send ('FAGGOT CRY U SUCK LOSER GETTING PRESSED OUTTA CHAT')
    await ctx.send ('STOP FUCKING MEXICAN GRANDMAS')
    await ctx.send ('YOU HAM FISTED TWIT CUNT FACE')
    await ctx.send ('CLEAN UR FATHER SHOES U SHITTY BOY UR ASS WTF TYPE FASTER PUSSY UR SPECIAL ED NIGGER HANDS R SWEATY ASF TYPE FASTER')
    await ctx.send ('ILL CUT UR VEINS OFF AND MAKE THEM MY SHOE LACES')
    await ctx.send ('EW WEIRD ASS DONKEY NIPPLE JUICE JUMBO MUNCHER')
    await ctx.send ('YOU GOT FUCKED IN THE ASS BY A SATANIC HIPPOPOTAMUS AND LIKED IT')
    await ctx.send ('BUM ASS NIGGA U WHORE BITCHMADE ASS BOY')
    await ctx.send ('PICK UR FACE UP OFF THE FLOOR NIGGA STOP BLEEDING')
    await ctx.send ('KEEP TYPING SUICIDAL BOZO FEMBOY')
    await ctx.send ('WEAK ASS LIZARD EATER')
    await ctx.send ('WORTHLESS PAKISTIAN PACKER')
    await ctx.send ('ILL PLAY A GAME OF CHESS OF UR CORPSE 🗡️')
    await ctx.send ('DONT LOOK AT ME QUEER ILL GOUGE UR EYES OFF')
    await ctx.send ('IMMA LIGHT UR CASKET ON FIRE ')
    await ctx.send ('PICK UR FACE UP OFF THE FLOOR NIGGA STOP BLEEDING')
    await ctx.send ('BIG ASS GORILLA TITTY MILK JUICER')
    await ctx.send ('IM IN UR HOUSE SLUT BITCH ASS CHILD MOLESTER')
    await ctx.send ('DIRTY BITCH BOY WHAT U GONNA DO SUM SON LOSER CANT COMPETE WITH ME')
    await ctx.send ('DONT SLOW DOWN KEEP THE PARTY GOINGMY SON SLOWING DOWN KEEP IT UP SON FOCUS')
    await ctx.send ('THIS IS UR END FAGGOT LOL CRY LZZZ')
    await ctx.send ('LMAOOO SON GETTING COOKED LOL UR SO ASS LOSER UR GARBAGE STOP TRYNA PRESSURE ME IM A GOD')
    await ctx.send ('👹ILL RUN U SON GET ON UR HANDS AND KNEES AND BEG FOR FORGIVNESS HOE BOY')
    await ctx.send ('PUSSY THOUGHT HE STOOD A CHANCE AGAINST ME LMFAO0O00O TROLL')
    await ctx.send ('EWWWW WEAK ASS CUNT MOUTH NIGGA CARRYING 5 YEARS WORTH OF CUM IN HIS MOUTH RN')
    await ctx.send ('SCRAWNY JAW NIGGA ILL BREAK UR EYELIDS OFF')
    await ctx.send ('YOUR BLACK AS SHIT 🖕 SEND UR RELATIVES MONKEY BIG NOSE FAT HEAD')
    await ctx.send ('HEAVY BODY U UGLY WHORE U LIKE DOG BALLS')
    await ctx.send ('ILL BEHEAD U DUMB SHIT BASTARD SHUT YO ASS UP CUNT U STAND A CHANCE AGAINST ME PUSSY ASS FAGGOT LOL NIGGA')
    await ctx.send ('SLUT CAT FUCKER DIDNT U HAVE SEX WITH A KOALA 🖕😭🖕')
    await ctx.send ('WEAK ASS AUTISTIC CUNT FAGGOT NIGGA FUCK UP FOCUS')
    await ctx.send ('LAME ASS WHORE ILL RAPE YOUR MOM WITH A SHOVEL')
    await ctx.send ('I FEEL BAD FOR U FAGGOT INSECURE FREAK DIDNT U BEG ME FOR NUDES COWGIRL')
    await ctx.send ('IM CRYING CUZ U SO HORSE SHIT LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOLLLLLLLLLLLL')
    await ctx.send ('STFU PUSSY BOOGIE MAN CREATURE')
    await ctx.send ('FOCUS BITCH SQUID NOSE ASS NIGGA ILL CUT UR FUCKING THROAT')
    await ctx.send ('DEFORMED VARMENT FAGGOT U NOT BETTER THAN ME PUSSY')
    await ctx.send ('U GOT NO AIM IMMA SHOOT UR FACE OFF')
    await ctx.send ('I ENSLAVED UR ENTIRE FAMILY UGLY ASS NIGGA')
    await ctx.send ('FOCUS ON UR OVERLORD SISSY CLITTY CUNT')
    await ctx.send ('PIPSQUEAK FUCKER')
    await ctx.send ('CRY BABY BAFOON BOO HOO LOSER')
    await ctx.send ('SON GETTING HIS SKULL CRACKED LMFAOOOO')
    await ctx.send ('SHUT THE FUCK SLAVE PEON BITCH ILL SLAUGHTER U WEAK ASS BUM ASS BITCH')
    await ctx.send ('MY SON GETTING SACRIFICED IN THE NAME OF HIS LORD')
    await ctx.send ('BITCHING THE FUCK OUT YO LAME HOE ASS WORD TO')
    await ctx.send ('ILL SEVER UR TENDONS IN UR FEET 🔪')
    await ctx.send ('NIGGA UR FUCKING TRASH NIGGA SLASH UR FUCKING NECK')
    await ctx.send ('WEAK ASS AUTISTIC CUNT FAGGOT NIGGA FUCK UP FOCUS')
    await ctx.send ('YO BITCH I HEARD YOU FART ON INFANTS')
    await ctx.send ('HOW DOES IT FEEL TO FUCK BABIES PEDO GROOMER')
    await ctx.send ('LAME ASS WHORE ILL RAPE YOUR MOM WITH A SHOVEL')
    await ctx.send ('ILL CHAIN SAW YOUR NIPPLES OFF')
    await ctx.send ('IM TIRED OF YO SLOW ASS GET FASTER DWEEB')
    await ctx.send ('NIGGA BITCHING CUZ HE GETTING HIS SOUL SNATCHED')
client.run(token, bot=False)